# Generated by Django 5.2 on 2025-08-14 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendabox',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaagenda', models.DateField(db_column='fechaAgenda')),
                ('horainicioagenda', models.TimeField(db_column='horaInicioAgenda')),
                ('horafinagenda', models.TimeField(blank=True, db_column='horaFinAgenda', null=True)),
                ('habilitada', models.IntegerField(db_column='Habilitada')),
                ('esMedica', models.IntegerField(db_column='esMedica')),
                ('nombre_responsable', models.CharField(blank=True, db_column='responsable', max_length=255, null=True)),
                ('observaciones', models.TextField(blank=True, db_column='observacion', null=True)),
            ],
            options={
                'db_table': 'agendabox',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Atenamb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMedico', models.IntegerField()),
                ('idBox', models.CharField(max_length=32)),
                ('fecha', models.DateField()),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
            ],
            options={
                'db_table': 'atenamb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('idbox', models.AutoField(db_column='idBox', primary_key=True, serialize=False)),
                ('estadobox', models.CharField(blank=True, db_column='estadoBox', max_length=20, null=True)),
                ('pasillobox', models.CharField(blank=True, db_column='pasilloBox', max_length=20, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'box',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('idespecialidad', models.AutoField(db_column='idEspecialidad', primary_key=True, serialize=False)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'especialidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogAtenamb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atenamb_id', models.IntegerField()),
                ('fecha_hora', models.DateTimeField()),
                ('accion', models.CharField(choices=[('INSERT', 'Insert'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=6)),
            ],
            options={
                'db_table': 'log_atenamb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('idmedico', models.AutoField(db_column='idMedico', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'medico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipobox',
            fields=[
                ('idtipobox', models.AutoField(db_column='idTipoBox', primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tipobox',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BoxTipoBox',
            fields=[
                ('idbox', models.ForeignKey(db_column='idBox', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='yggdrasilApp.box')),
                ('tipoprincipal', models.BooleanField(db_column='tipoPrincipal', default=False)),
            ],
            options={
                'db_table': 'boxtipobox',
                'managed': False,
            },
        ),
    ]
