# Generated by Django 5.2 on 2025-08-20 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yggdrasilApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialModificacionesBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_box', models.IntegerField(db_column='id_box')),
                ('usuario', models.CharField(max_length=100)),
                ('accion', models.CharField(choices=[('CREACION', 'Creación'), ('MODIFICACION', 'Modificación'), ('INHABILITACION', 'Inhabilitación'), ('HABILITACION', 'Habilitación'), ('ELIMINACION', 'Eliminación')], max_length=50)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('campo_modificado', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historial_modificaciones_box',
                'ordering': ['-fecha'],
            },
        ),
    ]
