# Generated by Django 5.2 on 2025-08-20 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yggdrasilApp', '0002_historialmodificacionesbox'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historialmodificacionesbox',
            table='historial_box',
        ),
    ]
