# Generated by Django 5.1 on 2025-04-28 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yggdrasilApp', '0002_boxtipobox'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Boxtipobox',
        ),
    ]
