# Generated by Django 5.1 on 2025-04-28 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yggdrasilApp', '0003_delete_boxtipobox'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cita',
        ),
    ]
