# Generated by Django 5.1 on 2025-05-18 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yggdrasilApp', '0006_atenamb_logatenamb'),
        ('yggdrasilApp', '0006_atenamb_logatenamb_delete_paciente'),
    ]

    operations = [
    ]
