# Generated by Django 5.2 on 2025-05-23 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yggdrasilApp', '0007_merge_20250518_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendabox',
            options={},
        ),
    ]
