# Generated by Django 5.2 on 2025-05-23 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yggdrasilApp', '0007_merge_20250518_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaNoMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaInicioReserva', models.TimeField()),
                ('horaFinReserva', models.TimeField()),
                ('nombreResponsable', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yggdrasilApp.agendabox')),
            ],
            options={
                'db_table': 'reservanomedica',
            },
        ),
    ]
