# Generated by Django 5.2 on 2025-05-23 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yggdrasilApp', '0008_reservanomedica'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReservaNoMedica',
        ),
    ]
